# Generated by Django 4.2.18 on 2025-04-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhour',
            name='hours_volunteered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
