# Generated by Django 4.2.18 on 2025-02-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='max_volunteers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FILLED', 'Filled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=10),
        ),
    ]
