# Generated by Django 4.2.18 on 2025-04-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_rsvp_migration'),
        ('opportunities', '0005_remove_event_attendees_event_max_attendees_and_more'),
    ]

    operations = [
    ]
