# Generated by Django 4.2.18 on 2025-04-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0007_alter_rsvp_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('EDU', 'Education'), ('ENV', 'Environment'), ('HEA', 'Health'), ('ANI', 'Animals'), ('ART', 'Arts'), ('COM', 'Community Development')], default='COM', max_length=3),
        ),
    ]
