# Generated by Django 5.0.6 on 2025-06-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_opportunity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='commitment_hours',
            field=models.IntegerField(blank=True, help_text='Hours per week', null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='category',
            field=models.CharField(choices=[('EDU', 'Education'), ('ENV', 'Environment'), ('HEA', 'Health'), ('ANI', 'Animals'), ('ART', 'Arts'), ('COM', 'Community Development'), ('DRE', 'Disaster Relief'), ('HUM', 'Human Rights'), ('OTH', 'Other')], default='COM', max_length=3),
        ),
    ]
